### ISSUE TITLE
Crazy accelerometer

### ISSUE THREAD

**Issue by Spettacolo83** [moflac/360-stereo#1]
Hi moflac!
Thank you for your library.
I would like to implement it on my project but on new Chrome the accelerometer/gyroscope move the camera in a crazy way.
I'm testing on Samsung S8.

**Comment by moflac** [comment]
Well, it's not my library exactly. The stereo component is from https://github.com/oscarmarinmiro/aframe-stereo-component. 
Accelerometer was fixed by using A-Frame version 0.8.0
And this seems to work correctly only with Firefox.

**Comment by moflac** [comment]
With 0.8.2 works now with mobile Chrome too.
